# Generated by Django 4.1 on 2022-09-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="user",
            new_name="follower",
        ),
    ]
