# Generated by Django 4.1 on 2022-09-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_user_follower_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="followee",
            new_name="followee_list",
        ),
    ]
