# Generated by Django 4.1 on 2022-09-25 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_followee_follower_followee_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followee_list",
            field=models.ManyToManyField(
                blank=True, related_name="followee_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
